import { Account, Budget, EMILoan, SplitGroup, Subscription, Transaction, UserProfile, UserSettings } from '../types';
import { SUPPORTED_CURRENCIES } from './formatters';

export const INITIAL_ACCOUNTS: Account[] = [
  {
    id: 'acc-1',
    name: 'Main Chase Checking',
    type: 'Bank',
    balance: 4280.50,
    currency: SUPPORTED_CURRENCIES[0], // USD
    color: '#3b82f6', // blue
    iconName: 'Landmark',
    accountNumberMasked: '•••• 8912',
  },
  {
    id: 'acc-2',
    name: 'Apple Titanium Card',
    type: 'Credit Card',
    balance: -840.20, // current spent
    currency: SUPPORTED_CURRENCIES[0],
    color: '#6366f1', // indigo
    iconName: 'CreditCard',
    creditLimit: 5000,
    statementDay: 15,
    dueDate: 5,
    apr: 18.24,
    accountNumberMasked: '•••• 4209',
  },
  {
    id: 'acc-3',
    name: 'High Yield Vault (4.8%)',
    type: 'Savings',
    balance: 14500.00,
    currency: SUPPORTED_CURRENCIES[0],
    color: '#10b981', // emerald
    iconName: 'ShieldCheck',
    accountNumberMasked: '•••• 6631',
  },
  {
    id: 'acc-4',
    name: 'Physical Cash Wallet',
    type: 'Cash',
    balance: 185.00,
    currency: SUPPORTED_CURRENCIES[0],
    color: '#f59e0b', // amber
    iconName: 'Wallet',
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    accountId: 'acc-1',
    amount: 14.85,
    type: 'EXPENSE',
    category: 'Food & Dining',
    merchant: 'Starbucks Reserve',
    date: '2026-10-01',
    notes: 'Morning matcha latte & croissant',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tx-2',
    accountId: 'acc-2',
    amount: 86.40,
    type: 'EXPENSE',
    category: 'Groceries',
    merchant: 'Whole Foods Market',
    date: '2026-09-30',
    notes: 'Weekly fresh produce & sourdough',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'tx-3',
    accountId: 'acc-1',
    amount: 3850.00,
    type: 'INCOME',
    category: 'Salary',
    merchant: 'Stripe Direct Deposit',
    date: '2026-09-28',
    notes: 'Bi-weekly engineering compensation',
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: 'tx-4',
    accountId: 'acc-2',
    amount: 22.99,
    type: 'EXPENSE',
    category: 'Subscriptions',
    merchant: 'Netflix 4K Ultra',
    date: '2026-09-27',
    isRecurring: true,
    notes: 'Monthly recurring streaming',
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: 'tx-5',
    accountId: 'acc-2',
    amount: 45.00,
    type: 'EXPENSE',
    category: 'Transportation',
    merchant: 'Uber Comfort',
    date: '2026-09-26',
    notes: 'Airport ride downtown',
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: 'tx-6',
    accountId: 'acc-1',
    amount: 120.00,
    type: 'EXPENSE',
    category: 'Utilities',
    merchant: 'Pacific Gas & Electric',
    date: '2026-09-24',
    notes: 'September electricity bill',
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: 'tx-7',
    accountId: 'acc-2',
    amount: 149.99,
    type: 'EXPENSE',
    category: 'Shopping',
    merchant: 'Nike Store Downtown',
    date: '2026-09-22',
    notes: 'Running shoes Pegasus 41',
    createdAt: new Date(Date.now() - 86400000 * 9).toISOString(),
  },
  {
    id: 'tx-8',
    accountId: 'acc-1',
    amount: 65.50,
    type: 'EXPENSE',
    category: 'Food & Dining',
    merchant: 'Ippudo Ramen',
    date: '2026-09-20',
    notes: 'Dinner with Alex & Sam',
    createdAt: new Date(Date.now() - 86400000 * 11).toISOString(),
  },
];

export const INITIAL_BUDGETS: Budget[] = [
  {
    id: 'b-1',
    name: 'Total Monthly Spend',
    category: 'ALL',
    limitAmount: 2200,
    period: 'MONTHLY',
    alertThreshold: 0.8,
  },
  {
    id: 'b-2',
    name: 'Food & Dining',
    category: 'Food & Dining',
    limitAmount: 450,
    period: 'MONTHLY',
    alertThreshold: 0.85,
  },
  {
    id: 'b-3',
    name: 'Groceries & Supplies',
    category: 'Groceries',
    limitAmount: 400,
    period: 'MONTHLY',
    alertThreshold: 0.8,
  },
  {
    id: 'b-4',
    name: 'Shopping & Discretionary',
    category: 'Shopping',
    limitAmount: 350,
    period: 'MONTHLY',
    alertThreshold: 0.75,
  },
];

export const INITIAL_SUBSCRIPTIONS: Subscription[] = [
  {
    id: 'sub-1',
    name: 'Netflix Premium 4K',
    merchant: 'Netflix',
    amount: 22.99,
    currencyCode: 'USD',
    accountId: 'acc-2',
    billingCycle: 'MONTHLY',
    nextBillingDate: '2026-10-27',
    category: 'Entertainment',
    status: 'ACTIVE',
    reminderDaysBefore: 2,
    iconName: 'Tv',
  },
  {
    id: 'sub-2',
    name: 'Spotify Duo Plan',
    merchant: 'Spotify',
    amount: 14.99,
    currencyCode: 'USD',
    accountId: 'acc-2',
    billingCycle: 'MONTHLY',
    nextBillingDate: '2026-10-14',
    category: 'Entertainment',
    status: 'ACTIVE',
    reminderDaysBefore: 3,
    iconName: 'Music',
  },
  {
    id: 'sub-3',
    name: 'Google One 2TB + AI',
    merchant: 'Google',
    amount: 19.99,
    currencyCode: 'USD',
    accountId: 'acc-1',
    billingCycle: 'MONTHLY',
    nextBillingDate: '2026-10-08',
    category: 'Utilities',
    status: 'ACTIVE',
    reminderDaysBefore: 1,
    iconName: 'Cloud',
  },
  {
    id: 'sub-4',
    name: 'Equinox Fitness Club',
    merchant: 'Equinox',
    amount: 165.00,
    currencyCode: 'USD',
    accountId: 'acc-1',
    billingCycle: 'MONTHLY',
    nextBillingDate: '2026-10-01',
    category: 'Healthcare',
    status: 'ACTIVE',
    reminderDaysBefore: 2,
    iconName: 'Dumbbell',
  },
  {
    id: 'sub-5',
    name: 'GitHub Copilot Individual',
    merchant: 'GitHub',
    amount: 10.00,
    currencyCode: 'USD',
    accountId: 'acc-2',
    billingCycle: 'MONTHLY',
    nextBillingDate: '2026-10-18',
    category: 'Other',
    status: 'PAUSED',
    reminderDaysBefore: 2,
    iconName: 'Code',
  },
];

export const INITIAL_SPLIT_GROUPS: SplitGroup[] = [
  {
    id: 'grp-1',
    name: 'Lake Tahoe Cabin Trip',
    description: 'Weekend getaway with friends',
    avatarColor: '#0ea5e9',
    members: [
      { id: 'mem-me', name: 'You (Host)', avatarColor: '#3b82f6', upiIdOrHandle: 'vault.user@okhdfcbank' },
      { id: 'mem-2', name: 'Liam Vance', email: 'liam@example.com', avatarColor: '#10b981', upiIdOrHandle: 'liam.vance@upi' },
      { id: 'mem-3', name: 'Maya Patel', email: 'maya@example.com', avatarColor: '#ec4899', upiIdOrHandle: 'mayap@oksbi' },
      { id: 'mem-4', name: 'David Cho', email: 'david@example.com', avatarColor: '#f59e0b', upiIdOrHandle: 'david.cho@paytm' },
    ],
    expenses: [
      {
        id: 'exp-1',
        groupId: 'grp-1',
        title: 'Airbnb 3-Night Rental',
        amount: 840.00,
        paidByMemberId: 'mem-me',
        splitType: 'EQUAL',
        shares: { 'mem-me': 210, 'mem-2': 210, 'mem-3': 210, 'mem-4': 210 },
        date: '2026-09-22',
        notes: 'Cozy lakeside chalet with fireplace',
      },
      {
        id: 'exp-2',
        groupId: 'grp-1',
        title: 'Safeway Groceries & BBQ Supplies',
        amount: 220.00,
        paidByMemberId: 'mem-2',
        splitType: 'EQUAL',
        shares: { 'mem-me': 55, 'mem-2': 55, 'mem-3': 55, 'mem-4': 55 },
        date: '2026-09-23',
      },
    ],
    settlements: [
      {
        id: 'stl-1',
        groupId: 'grp-1',
        fromMemberId: 'mem-3',
        toMemberId: 'mem-me',
        amount: 210.00,
        date: '2026-09-24',
        method: 'UPI',
      },
    ],
    createdAt: '2026-09-20',
  },
  {
    id: 'grp-2',
    name: 'Apartment 402 Roommates',
    description: 'Shared rent, Wi-Fi & cleaning',
    avatarColor: '#8b5cf6',
    members: [
      { id: 'mem-me', name: 'You', avatarColor: '#3b82f6', upiIdOrHandle: 'vault.user@okhdfcbank' },
      { id: 'mem-roomie', name: 'Elena Rostova', avatarColor: '#14b8a6', upiIdOrHandle: 'elena.rostova@paypal' },
    ],
    expenses: [
      {
        id: 'exp-3',
        groupId: 'grp-2',
        title: 'Gigabit Fiber Internet',
        amount: 80.00,
        paidByMemberId: 'mem-me',
        splitType: 'EQUAL',
        shares: { 'mem-me': 40, 'mem-roomie': 40 },
        date: '2026-09-15',
      },
    ],
    settlements: [],
    createdAt: '2026-08-01',
  },
];

export const INITIAL_EMI_LOANS: EMILoan[] = [
  {
    id: 'emi-1',
    name: 'Tesla Model Y Auto Loan',
    lender: 'Chase Auto Finance',
    principal: 38000,
    annualInterestRate: 5.49,
    tenureMonths: 60,
    emiAmount: 725.60,
    startDate: '2025-06-01',
    category: 'Car Loan',
  },
  {
    id: 'emi-2',
    name: 'MacBook Pro M4 Max 16"',
    lender: 'Apple Citizen One (0% APR)',
    principal: 3499,
    annualInterestRate: 0.0,
    tenureMonths: 12,
    emiAmount: 291.58,
    startDate: '2026-02-01',
    category: 'Gadget EMI',
  },
];

export const INITIAL_PROFILES: UserProfile[] = [
  {
    id: 'prof-personal',
    name: 'Rushabh (Personal)',
    type: 'PERSONAL',
    avatarColor: '#10b981',
    email: 'avengerrush0106@gmail.com',
    isPrimary: true,
  },
  {
    id: 'prof-business',
    name: 'Waufle Studio LLC',
    type: 'BUSINESS',
    avatarColor: '#6366f1',
    email: 'rushabh@wauflevault.app',
    isPrimary: false,
  },
  {
    id: 'prof-family',
    name: 'Household & Family',
    type: 'FAMILY',
    avatarColor: '#f59e0b',
    isPrimary: false,
  },
];

export const INITIAL_USER_SETTINGS: UserSettings = {
  defaultCurrency: SUPPORTED_CURRENCIES[0],
  theme: 'dark',
  themeConfig: {
    style: 'clear-glass', // Volumetric 3D Frosted Octane Render
    customPrimaryColor: '#10b981',
    customAccentColor: '#6366f1',
    backgroundBlur: 16,
    glassRefractionEnabled: true,
    crazyAnimations: true,
  },
  biometricLockEnabled: false,
  pinCode: '1234',
  autoLockMinutes: 5,
  driveSyncEnabled: true,
  lastSyncDate: '2026-10-01 08:20 AM',
  userName: 'Rushabh',
  userEmail: 'avengerrush0106@gmail.com',
  connectedGoogleAccount: 'avengerrush0106@gmail.com',
  hideBalancesOnLaunch: false,
  notifications: {
    paymentRemindersEnabled: true,
    upcomingSubscriptionAlerts: true,
    dailyVelocityDigest: true,
    budgetThresholdAlerts: true,
    creditCardDueAlerts: true,
    hapticFeedbackEnabled: true,
  },
};

